// Class automatically generated by Dev-C++ New Class wizard

#ifndef DICTIONARYOPS_H
#define DICTIONARYOPS_H
#include <string> 
#include <vector> 
#include <iostream> 
#include<fstream>
#include <sstream>

class dictionaryops
{
	public:
		dictionaryops();
		~dictionaryops();
		void addWordToCSV(const std::string& word, const std::string& synonymsInput);
};

#endif // DICTIONARYOPS_H
