// Class automatically generated by Dev-C++ New Class wizard

#ifndef MODIFYCONTENT_H
#define MODIFYCONTENT_H
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <algorithm>
#include <limits>
#include <sstream>
#include<cstdlib>
// No description
class modifyContent
{
	public:
		// class constructor
		modifyContent();
		// class destructor
		~modifyContent();
		std::vector<std::string> modifyContent::readFile();
		void modifyContent::writeFile(const std::vector<std::string>& lines);
		void modifyContent::editFile();
};

#endif // MODIFYCONTENT_H
