// Class automatically generated by Dev-C++ New Class wizard

#ifndef SYNONYMS_H
#define SYNONYMS_H
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <iomanip>
#include <algorithm>

class synonyms
{
	public:
		synonyms();
		~synonyms();
		void synonyms::findSynonyms(std::string searchWord);
		std::string synonyms::toLower(std::string str);
		std::string synonyms::trim(const std::string& str);
};

#endif // SYNONYMS_H
